[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/app/supervisord.pid

[program:cron_job]
command=python telegram_main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/cron.log
stderr_logfile=/app/logs/cron_error.log

[program:webhook_server]
command=python telegram_bot_server.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/webhook.log
stderr_logfile=/app/logs/webhook_error.log

