# Generated by Django 5.2.11 on 2026-02-04 22:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "service_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("group_name", models.CharField(max_length=50)),
                ("icon", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_code", models.CharField(max_length=20, unique=True)),
                ("plan_name", models.CharField(max_length=100)),
                ("max_vehicles", models.IntegerField(blank=True, null=True)),
                ("allow_csv_export", models.BooleanField(default=True)),
                ("allow_pdf_export", models.BooleanField(default=False)),
                ("allow_sms_reminder", models.BooleanField(default=False)),
                ("monthly_price", models.BigIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro"), ("pro+", "Pro+")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "indexes": [
                    models.Index(fields=["tier"], name="khodroban_u_tier_062c75_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "connection_code",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Setting",
                "verbose_name_plural": "Telegram Settings",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "subscription_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="khodroban.subscriptionplan",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("vehicle_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("plate_number", models.CharField(max_length=20)),
                ("current_km", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["-updated_at"],
                "unique_together": {("user_profile", "plate_number")},
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("service_date", models.DateField()),
                ("service_date_gregorian", models.DateField()),
                ("service_km", models.IntegerField()),
                ("total_cost", models.BigIntegerField(default=0)),
                ("general_note", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["-service_date_gregorian"],
            },
        ),
        migrations.CreateModel(
            name="ReminderSetting",
            fields=[
                (
                    "reminder_setting_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("interval_km", models.IntegerField(default=5000)),
                ("interval_days", models.IntegerField(default=90)),
                ("warning_km_before", models.IntegerField(default=500)),
                ("warning_days_before", models.IntegerField(default=7)),
                (
                    "reminder_mode",
                    models.CharField(
                        choices=[
                            ("km", "KM-based"),
                            ("time", "Time-based"),
                            ("both", "Both"),
                        ],
                        default="time",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Setting",
                "verbose_name_plural": "Reminder Settings",
            },
        ),
        migrations.CreateModel(
            name="DailyExpense",
            fields=[
                ("expense_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("expense_date", models.DateField()),
                ("expense_date_gregorian", models.DateField()),
                ("amount", models.BigIntegerField()),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("km_at_expense", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Expense",
                "verbose_name_plural": "Daily Expenses",
                "ordering": ["-expense_date_gregorian"],
            },
        ),
        migrations.CreateModel(
            name="VehicleKmHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("km", models.IntegerField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("service", "Service"),
                            ("expense", "Expense"),
                            ("initial", "Initial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle KM History",
                "verbose_name_plural": "Vehicle KM Histories",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "service_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cost", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.service",
                    ),
                ),
                (
                    "service_type_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="khodroban.servicetype",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Item",
                "verbose_name_plural": "Service Items",
                "unique_together": {("service", "service_type_code")},
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("due_km", models.IntegerField(blank=True, null=True)),
                ("warning_days_before", models.IntegerField(default=7)),
                ("warning_km_before", models.IntegerField(default=500)),
                ("status", models.CharField(default="ok", max_length=20)),
                ("message", models.TextField(blank=True, null=True)),
                ("source", models.CharField(default="manual", max_length=20)),
                ("dismissed", models.BooleanField(default=False)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.userprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "indexes": [
                    models.Index(
                        fields=["user_profile"], name="khodroban_r_user_pr_0f4609_idx"
                    ),
                    models.Index(
                        fields=["vehicle"], name="khodroban_r_vehicle_fadb57_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="khodroban_r_due_dat_ff17cb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="khodroban_r_status_e4649d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=50,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "notification_channels",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khodroban.userprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "indexes": [
                    models.Index(
                        fields=["user_profile", "read"],
                        name="khodroban_n_user_pr_c175ed_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="khodroban_n_sent_at_c3f591_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="khodroban_n_created_813e07_idx"
                    ),
                ],
            },
        ),
    ]
