# Generated by Django 5.2.11 on 2026-02-12 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khodroban', '0003_seed_service_types_and_expense_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePreset',
            fields=[
                ('preset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_types', models.ManyToManyField(blank=True, help_text='انواع سرویس\u200cای که با انتخاب این preset انتخاب می\u200cشوند', related_name='presets', to='khodroban.servicetype')),
            ],
            options={
                'verbose_name': 'Service Preset',
                'verbose_name_plural': 'Service Presets',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
