# Generated by Django 5.2.11 on 2026-02-12

import django.db.models.deletion
from django.db import migrations, models


def remove_duplicate_service_items(apps, schema_editor):
    """حذف ردیف‌های تکراری (service_id, service_type_id) تا unique_together قابل اعمال باشد."""
    ServiceItem = apps.get_model("khodroban", "ServiceItem")
    seen = set()
    to_delete = []
    for row in ServiceItem.objects.order_by("id"):
        key = (row.service_id, row.service_type_id)
        if key in seen:
            to_delete.append(row.id)
        else:
            seen.add(key)
    ServiceItem.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("khodroban", "0005_rename_expense_id_dailyexpense_id_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_service_items, migrations.RunPython.noop),
        # اول unique_together را به (service, service_type) تغییر بده تا در _remake_table
        # new_model دیگر به service_type_code اشاره نکند (در غیر این صورت FieldDoesNotExist).
        migrations.AlterUniqueTogether(
            name="serviceitem",
            unique_together={("service", "service_type")},
        ),
        migrations.RemoveField(
            model_name="serviceitem",
            name="service_type_code",
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="khodroban.service",
            ),
        ),
    ]
