# Generated by Django 5.2.11 on 2026-02-12 20:30

import django.db.models.deletion
import django.utils.timezone
import khodroban.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("khodroban", "0006_serviceitem_remove_service_type_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="icon_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color, e.g. #FF5733",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="FontAwesome icon name, e.g. car",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="icon_style",
            field=models.CharField(
                blank=True,
                default="solid",
                help_text="FontAwesome style: solid, regular, brands",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.FileField(
                        help_text="JPG/PNG/WebP, max 5MB",
                        max_length=255,
                        upload_to=khodroban.models.vehicle_image_upload_path,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="khodroban.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Image",
                "verbose_name_plural": "Vehicle Images",
                "ordering": ["display_order", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("vehicle", "is_default"),
                        name="unique_vehicle_default_image",
                    )
                ],
            },
        ),
    ]
