# Generated by Django 5.2.11 on 2026-02-12 20:43

import khodroban.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("khodroban", "0007_vehicle_icon_and_vehicle_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleimage",
            name="image",
            field=models.ImageField(
                help_text="JPG/PNG/WebP, max 5MB",
                max_length=255,
                upload_to=khodroban.models.vehicle_image_upload_path,
            ),
        ),
    ]
