# Generated by Django 5.2.11 on 2026-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("khodroban", "0008_vehicle_image_use_imagefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="icon_color_secondary",
            field=models.CharField(
                blank=True,
                help_text="Duotone secondary layer hex color",
                max_length=20,
                null=True,
            ),
        ),
    ]
