# Generated by Django 5.2.11 on 2026-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("khodroban", "0009_vehicle_icon_color_secondary"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
