# Generated by Django 5.2.11 on 2026-02-15 19:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReminderDueEventOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(default="reminder.due.detected.v1", max_length=64),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Reminder Due Event Outbox",
                "verbose_name_plural": "Reminder Due Event Outbox",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["processed_at"], name="reminders_r_process_a6f81b_idx"
                    )
                ],
            },
        ),
    ]
